name: AUMA Messe Notifier

on:
  schedule:
    - cron: "0 7 * * *"   # Jeden Tag um 07:00 Uhr UTC
  workflow_dispatch:       # Manueller Start möglich

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Notifier Script
        run: python api.py
